import { Inject, Injectable, ConflictException } from '@nestjs/common';
import type { IProductRepository } from '../../domain/interfaces/product-repository.interface.js';
import { CreateProductDto } from '../dtos/create-product.dto.js';
import { ProductResponseDto } from '../dtos/product-response.dto.js';
import { PrismaService } from '../../../../prisma/prisma.service.js';

@Injectable()
export class CreateProductUseCase {
  constructor(
    @Inject('IProductRepository')
    private readonly productRepository: IProductRepository,
    private readonly prisma: PrismaService,
  ) {}

  async execute(data: CreateProductDto): Promise<ProductResponseDto> {
    if (!data.barcode) {
      data.barcode = await this.productRepository.generateUniqueBarcode(data.shopId);
    }
    if (data.barcode) {
      const existingBarcode = await this.productRepository.findByBarcode(data.barcode, data.shopId);
      if (existingBarcode) {
        throw new ConflictException({ message: 'Ce code-barres est déjà utilisé', field: 'barcode' });
      }
    }

    const sku = `SK-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).substring(2, 6).toUpperCase()}`;
    const product = await this.productRepository.create({ ...data, sku });

    // Crée automatiquement une dépense si le produit est créé avec un stock initial
    const initialQty = data.stockQty ?? 0;
    if (initialQty > 0 && data.buyingPrice > 0) {
      await this.prisma.expense.create({
        data: {
          title: `Stock initial — ${data.name}`,
          category: 'STOCK_INITIAL',
          amount: initialQty * data.buyingPrice,
          date: new Date(),
          description: `${initialQty} unité(s) × ${data.buyingPrice} XOF`,
          shopId: data.shopId,
          isAutoGenerated: true,
          isRecurring: false,
        },
      });
    }

    return ProductResponseDto.fromDomain(product);
  }
}
