-- Add new expense categories for auto-generated expenses
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'PURCHASE_ORDER';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'STOCK_INITIAL';

-- Add isAutoGenerated column to expenses (read-only flag for system-created expenses)
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
